version: '3'
services:
  core.php:
    build:
      context: ./
      dockerfile: ./config/docker/Dockerfile
    image: core-7.4/php
    volumes:
      - .:/var/www/html
      - ./config/docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - core
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
      - ./config/docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - core
  mysql:
    image: mysql:5.7.32
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - core-mysql:/var/lib/mysql/
      - ./config/docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - core
networks:
  core:
    driver: bridge
volumes:
  core-mysql:
    driver: local
