version: '3'
services:
  core.php:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: core-8.1/php
    environment:
      XDEBUG_MODE: '${CORE_XDEBUG_MODE:-off}'
      XDEBUG_CONFIG: '${CORE_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

    networks:
      - core
  nginx:
    image: nginx:alpine
    ports:
      - '${CORE_PORT:-80}:80'
      - '${CORE_SSL_PORT:-443}:443'
    volumes:
      - .:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - core
  mysql:
    image: mysql:5.7.32
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - core-mysql:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - core
networks:
  core:
    driver: bridge
volumes:
  core-mysql:
    driver: local
